### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by brad-decker** [ConciergeAuctions/respondable#14]
I was thinking we could add a 'server' breakpoint config that, if present, would bypass the check for matchMedia polyfill and would just call the callback with a special value that we could then account for in userland. something like. 

```js
import respondable from 'respondable';

const breakpointObject = {
  server: 'server', 
  'screen and (max-width: 413px)': 'smallest',
  'screen and (min-width: 414px) and (max-width: 767px)': 'small',
  'screen and (min-width: 768px) and (max-width: 1079px)': 'medium',
  'screen and (min-width: 1080px) and (max-width: 1399px)': 'large',
  'screen and (min-width: 1400px)': 'largest',
};

const callback = function(active) {
  if (active === 'server') {
     // decide how to give a size for your configuration on server
  }
  console.log(active);
};

const destroy = respondable(breakpointObject, callback);

// remove registered listeners
destroy();
```

Thoughts ?

**Comment by brad-decker** [comment]
@Nathan-Schwartz could you check this when you get a chance.

**Comment by Nathan-Schwartz** [comment]
After some discussion we found a different approach. In our applications we dispatch the current viewport to redux in the respondable callback. By defaulting the redux viewport state to "server" we can accomplish the same thing Brad was talking about, in our codebase. We don't actually want respondable to run until our app mounts in the client anyways.

Tagging @brad-decker in case I left anything out 👍
