### ISSUE TITLE
[RFC] Should priority options require all breakpoint names to be present?

### ISSUE THREAD

**Issue by Nathan-Schwartz** [ConciergeAuctions/respondable#8]
Making all breakpoint names required could be limiting if there are breakpoints that are there to supplement others, such as an orientation or aspect ratio query. 

Another use case would be when breakpoints are being deprecated. Leaving them in `active` would allow them to still be used where needed, and excluding them from `priority` would allow it to be more reliable and current.

One solution that is possible without changing the constraints of `priority` would be giving the utility / deprecated breakpoints a low priority, but it is my opinion that this solution is more limiting and not as clean.

**Comment by Nathan-Schwartz** [comment]
@brad-decker I haven't thought of any disadvantages yet, so I'm moving forward with this.

**Comment by brad-decker** [comment]
@Nathan-Schwartz - I honestly tried to think about this but given your expertise in this subject i'm completely comfortable with you moving forward. I'd suggest leaving this open for now, but go forward with your hypothesis and we'll reconvene on this issue in retrospect for validated learning.

**Comment by Nathan-Schwartz** [comment]
Sounds good to me 👍
